import { ClerkProvider } from "@clerk/nextjs";
import React from "react";
import "@/app/globals.css";
import ThemeInitializer from "@/components/shared/ThemeInitializer";

export const metadata = {
  title: 'Vibe Share',
  description: 'Generated by Vibe Share',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className="flex min-h-screen items-center justify-center bg-neutral-50 dark:bg-neutral-950 antialiased text-neutral-900 dark:text-neutral-50 transition-colors duration-250">
          <ThemeInitializer />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}